customers/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.update, name='update'),
]

homepage/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.homepage, name='index'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('homepage.urls', 'homepage'), namespace='homepage')),
    path('customers/', include(('customers.urls', 'customers'), namespace='customers')),
    path('admin/', admin.site.urls),
]

customers/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Customer(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    address = models.CharField(max_length=255, blank=True, null=True)
    date_of_birth = models.DateField(null=True, blank=True)

customers/forms.py
from django import forms

from .models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('user', 'address', 'date_of_birth')

customers/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.http.response import HttpResponseRedirect
from django.urls import reverse

from .forms import CustomerForm
from .models import Customer

# Create your views here.
@require_http_methods(['GET'])
def index(request):
    customers = Customer.objects.all()
    return render(request, 'customers/index.html', {'customers': customers})


@require_http_methods(['GET', 'POST'])
def update(request, pk):
    customer = get_object_or_404(Customer, pk=pk)

    if request.method == 'GET':
        form = CustomerForm(instance=customer)
        return render(request, 'customers/update.html', {'customer': customer, 'form': form})

    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('customers:update', kwargs={'pk': pk}))
        return render(request, 'customers/update.html', {'customer': customer, 'form': form})

homepage/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, 'homepage/index.html')

customers/templates/customers/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer List</title>
</head>
<body>
    <h1>Customers List</h1>
    <table>
        <thead>
            <tr>
                <th>Created</th>
                <th>Modified</th>
                <th>User</th>
                <th>Address</th>
                <th>Date of Birth</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.created }}</td>
                    <td>{{ customer.modified }}</td>
                    <td>{{ customer.user.pk }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.date_of_birth }}</td>
                    <td><a href="{% url "customers:update" pk=customer.pk %}">Update</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

customers/templates/customers/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Customer</title>
</head>
<body>
    <h1>Update Customer:</h1>
    <span><a href="{% url "customers:index" %}">Back to customer list</a></span>
    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Project!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>